### ISSUE TITLE
Can't get the the project to install with cocoa pods

### ISSUE THREAD

**Issue by JoshAtAvenza** [forcedotcom/DeskMobileSDK-iOS#24]
Neither of the suggested methods for adding this project to a Podfile work:

(from this repo's README and example project)

pod 'DeskKit', '~> 3.0.0’ 

or (from the desk.com getting started page)

pod ‘DeskKit’, :git => 'https://github.com/forcedotcom/DeskMobileSDK-iOS'

Using the first tells me:

[!] Unable to find a specification for `DeskKit (~> 3.0.0)`

Using the second tells me:

[!] Unable to find a specification for 'DeskKit'.

I have installed the most recent version of cocoa pods.  Beyond that I am unsure what to do.  I have been able to install the related DeskCommon and DeskAPIClient libraries via cocoa pods.

**Comment by eldark88** [comment]
I verified the podspecs for DeskKit and everything seems up to date. It looks like your local copy of specs are not up to date. Can you verify it by running this command?
```
pod list | grep 'DeskKit'
```
If the command doesn't return anything, then I recommend you to update spec repo by running following commands:
```
pod repo remove master --verbose
pod install --verbose
```
The second command will take some time to run, because it needs to clone spec repo.

**Comment by JoshAtAvenza** [comment]
Updating the spec repo worked! ... thanks!
